require("./bootstrap.js")
require("./slick.min.js")
require("./slider.js")
require("./bootstrap-colequalizer.js")
require("./col.js")
require("./app_secondary.js")
require("./jquery.smooth-scroll.min.js")
